parameters:
#    ull_image_tags.example.class: ULL\Bundle\ImageTagsBundle\Example

services:
#    ull_image_tags.example:
#        class: %ull_image_tags.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
